name: block_flow
description: block_flow
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.3.0
  injectable: ^2.4.0
  get_it: ^8.0.2

  domain:
    path: ./packages/domain

  data:
    path: ./packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_native_splash: ^2.3.10
  injectable_generator: ^2.4.0

dependency_overrides:
  meta: ^1.12.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/app/
